# Version of the config.yml
version: v2.0.0

# Name of the challenge
name: 'Geometric mean'

# Challenge difficulty: 10 - 500
difficulty: 15

# Enable inputbox to submit flag: true | false
enable_flag_input: false

# If the solution is a fix string (static flag) you can add it here
# flag: "This_iS_the_Solution"

# Skills related to the challenge: ["SQL injection","Web","Linux"]
skills: ['Cpp']

# Recommended readings
recommendations:
    http://en.cppreference.com/w/cpp/language/parameter_pack: 'Variadic templates'
    http://en.cppreference.com/w/cpp/language/template_argument_deduction: 'Template argument deduction'
    http://en.cppreference.com/w/cpp/language/adl: 'ADL'

# The emails of the Intellectual Property (IP) owners. Note that it is also possible that the owner is the same as the content creator.
owners: ["your@mail.com"]

# CRP Config
crp_config:
    controller:
        ports: ['5555/controller']
    solvable:
        # Required Linux capabilities (See http://man7.org/linux/man-pages/man7/capabilities.7.html for the full list).
        # For example ["SETGID","SETUID"]
        capabilities: ['SETGID','SETUID', 'AUDIT_WRITE']
        mem_limit: '200M' # Only set this if the default 100M is not enough (max 999M)
        ports: ['8888/http']
