# Version of the config.yml
version: "v2.0.0"

# Name of the challenge
name: 'Getting Started'

# Challenge difficulty: 10 - 500
difficulty: 10

# Enable inputbox to submit flag: true | false
enable_flag_input: false

# If the solution is a fix string (static flag) you can add it here
flag: "C0NGR4TULAT1ONS"

# Skills related to the challenge: ["SQL injection","Web","Linux"]
skills: ['Authentication', 'Web Security', 'Offensive', 'OWASP Top 10']

# Recommended readings
recommendations:
    https://blog.lastpass.com/2012/03/latest-review-of-security-issues-and.html/: 'New study - Passwords are still the weakest link'
    http://www.makeuseof.com/tag/7-password-mistakes-will-likely-get-hacked/: '7 Password Mistakes That Will Likely Get You Hacked'

# The emails of the Intellectual Property (IP) owners. Note that it is also possible that the owner is the same as the content creator.
owners: ['gergo.turcsanyi@avatao.com']

# CRP Config
crp_config:
    controller:
        # Required Linux capabilities (See http://man7.org/linux/man-pages/man7/capabilities.7.html for the full list).
        # For example ["SETGID","SETUID"]
        # capabilities: [] # Not needed if empty
        ports: ['5555/controller']
    solvable:
        # capabilities: [] # Not needed if empty
        ports: ['8888/http']
